CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](128) NOT NULL,
	[FirstName] [nvarchar](250) NULL,
	[LastName] [nvarchar](250) NULL,
	[Degree] [nvarchar](128) NULL,
	[ReviewerType] [nvarchar](128) NULL,
	[HomeAddressLine1] [nvarchar](128) NULL,
	[HomeAddressLine2] [nvarchar](128) NULL,
	[HomeCity] [nvarchar](50) NULL,
	[HomeState] [nvarchar](30) NULL,
	[HomeZip] [nvarchar](11) NULL,
	[HomeFaxNumber] [nvarchar](15) NULL,
	[Employer] [nvarchar](128) NULL,
	[Department] [nvarchar](128) NULL,
	[WorkEmail] [nvarchar](128) NULL,
	[WorkAddressLine1] [nvarchar](128) NULL,
	[WorkAddressLine2] [nvarchar](128) NULL,
	[WorkCity] [nvarchar](50) NULL,
	[WorkState] [nvarchar](30) NULL,
	[WorkZip] [nvarchar](11) NULL,
	[WorkPhoneNumber] [nvarchar](15) NULL,
	[WorkFaxNumber] [nvarchar](15) NULL,
	[ExperienceSummary] [nvarchar](max) NULL,
	[Email] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEndDateUtc] [datetime] NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
