CREATE TABLE [dbo].[Reviewers]
(
	[Id] NVARCHAR(128) NOT NULL PRIMARY KEY, 
    [UserId] NVARCHAR(128) NULL, 
	[FirstName] NVARCHAR(250) NULL, 
    [LastName] NVARCHAR(250) NULL, 
    [Degree] VARCHAR(35) NULL, 
    [ReviewerType] VARCHAR(35) NULL,        
    [HomeAddressLine1] VARCHAR(100) NULL, 
    [HomeAddressLine2] VARCHAR(100) NULL, 
	[HomeCity] VARCHAR(30) NULL,
    [HomeState] CHAR(2) NULL, 
    [HomeZip] VARCHAR(11) NULL, 
	[PhoneNumber] VARCHAR(15) NULL, 
    [FaxNumber] VARCHAR(15) NULL, 
    [Email] VARCHAR(100) NULL, 
    [Employer] VARCHAR(40) NULL, 
    [Department] VARCHAR(30) NULL, 
    [WorkAddressLine1] VARCHAR(100) NULL, 
	[WorkAddressLine2] VARCHAR(100) NULL, 
    [WorkCity] VARCHAR(30) NULL,
	[WorkState] CHAR(2) NULL,
    [WorkZip] VARCHAR(11) NULL, 
    [WorkPhoneNumber] VARCHAR(15) NULL, 
    [WorkFaxNumber] VARCHAR(15) NULL, 
    [WorkEmail] NCHAR(100) NULL, 
    [ExperienceSummary] VARCHAR(MAX) NULL, 
	[IsActive] BIT NULL, 
    CONSTRAINT [FK_Reviewers_User] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers]([Id])
)
