INSERT INTO AspNetRoles (Id, Name) VALUES (NEWID(), 'Declined Reviewer');

DECLARE @INVREV NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Invited Reviewer');
DECLARE @INVREV NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Declined Reviewer');