GO

DECLARE @ROLEID1 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Data Entry'),
		@ROLEID2 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Assigner'),
		@ROLEID3 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Principal Investigator'), 
		@ROLEID4 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Lit Review'), 
		@ROLEID5 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Review Coordinator'), 
		@ROLEID6 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'DSG PRM'), 
		@ROLEID7 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Mathematica Assigner'), 
		@ROLEID8 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'Reviewer'),
		@ROLEID9 NVARCHAR(128) = (SELECT ID FROM ASPNETROLES WHERE NAME = 'PreScreener')

INSERT INTO Permissions (Id, PermissionName) VALUES (8, 'AnswerPrescreen')


INSERT INTO Role_Permissions (PermissionID, RoleID, StatusID, Allowed) values (8, @ROLEID5, 2, cast(1 as Bit))
INSERT INTO Role_Permissions (PermissionID, RoleID, StatusID, Allowed) values (8, @ROLEID9, 2, cast(1 as Bit))

GO