CREATE PROCEDURE [dbo].[SPGetUserRoleByLoginName]
	@LoginName NVARCHAR(100)
AS
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN
	SELECT DISTINCT Name 
	  FROM AspNetUserRoles ANUR WITH (NOLOCK)
	  INNER JOIN AspNetUsers ANU WITH (NOLOCK) ON ANU.Id = ANUR.UserId
	  INNER JOIN AspNetRoles ANR WITH (NOLOCK) ON ANUR.RoleId = ANR.Id
	 WHERE 
	   ANU.UserName = @LoginName
END
GO
